### ISSUE TITLE
Парсер данных АЦП

### ISSUE THREAD

**Issue by CrinitusFeles** [a-styuf/oai_kpa_stm#3]
Что-то не так с парсером данных. До 15 пина работает по какому-то магическому алгоритму, к которому я подогнал свои значения и в принципе норм, но 15й канал нулевого АЦП отображается в первом АЦП, а 16 канал снова в нулевом.  Из-за того, что игнорируются пины земли разъема (17, 18) пришлось использовать костыли для нормального мапинга элементов списка.
При этом функция get_channels_values() совсем неприменима, т.к. полностью не соответствует замыкаемым пинам.
Казалось бы, поле self.table_values могло решить проблему, но это ловушка и, по всей видимости, рудимент, оставшийся от начальных версий, т.к. кроме инициализации поля с ним больше ничего не происходит.

В общем, нужна норм функция парсера каналов АЦП или хотя бы описании логики парсера.

**Comment by a-styuf** [comment]
Поправлено
